name: bugichat
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/translations/

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  get: ^4.6.5
  google_sign_in: ^6.0.2
  sign_in_with_apple: ^4.2.0
  firebase_auth: ^4.1.5
  firebase_core: ^2.9.0
  firebase_messaging: ^14.1.3
  firebase_storage: ^11.0.6
  flutter_screenutil: ^5.6.0
  firebase_crashlytics: ^3.0.6
  flutter_local_notifications: ^13.0.0
  shared_preferences: ^2.0.17
  cloud_firestore: ^4.5.0
  flutter_svg: ^2.0.0+1
  fluttertoast: ^8.1.2
  encrypt: ^5.0.1
  video_player: ^2.6.1
  url_launcher: ^6.1.10
  flutter_gif: ^0.0.4
  gif_view: ^0.3.1
  easy_localization: ^3.0.2
  restart_app: ^1.2.1
  flutter_phoenix: ^1.1.1
  image_picker: ^1.0.4
  tflite_flutter: ^0.10.3
  image: ^4.1.3

fonts:
  - family: Pretendard
    fonts:
      - asset: assets/font/Pretendard-Thin.ttf
        weight: 100
      - asset: assets/font/Pretendard-Light.ttf
        weight: 300
      - asset: assets/font/Pretendard-Regular.ttf
        weight: 400
      - asset: assets/font/Pretendard-Medium.ttf
        weight: 500
      - asset: assets/font/Pretendard-SemiBold.ttf
        weight: 600
      - asset: assets/font/Pretendard-Bold.ttf
        weight: 700
      - asset: assets/font/Pretendard-ExtraBold.ttf
        weight: 800
      - asset: assets/font/Pretendard-Black.ttf
        weight: 900


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
