// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVlK0439RuYvGQW6LUwo8v-ae2vRFtoQg',
    appId: '1:573792270276:web:86904782926fe2f66f1691',
    messagingSenderId: '573792270276',
    projectId: 'bugi-chat-apps',
    authDomain: 'bugi-chat-apps.firebaseapp.com',
    storageBucket: 'bugi-chat-apps.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsY-wDSfdtWwHw1qpaFaAg_4P71f3zvF0',
    appId: '1:573792270276:android:05ac12b239597c9e6f1691',
    messagingSenderId: '573792270276',
    projectId: 'bugi-chat-apps',
    storageBucket: 'bugi-chat-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQdckanGxergoVSgobjeNN4__8Yo8LoWY',
    appId: '1:573792270276:ios:72eb8b3ec14b2a6f6f1691',
    messagingSenderId: '573792270276',
    projectId: 'bugi-chat-apps',
    storageBucket: 'bugi-chat-apps.appspot.com',
    iosBundleId: 'com.bugichat.apps',
  );
}
